### ISSUE TITLE
Rendered SQL not shown in ZMI SQL Method 'Test' pane in error case

### ISSUE THREAD

**Issue by mvoppen** [zopefoundation/Products.ZSQLMethods#15]
When I test a SQL Method in Zope 4.1.1 ZMI I see the _Rendered SQL query code_ if the query was successful.
That is very helpful.
That _Rendered SQL query code_ is _not_ shown in error case. There it would be even more helpful.

**Comment by icemac** [comment]
This sounds like a nice feature. A pull request implementing it is welcome.
