### ISSUE TITLE
src/Shared/* is not part of coverage

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.ZSQLMethods#39]
It seems that https://github.com/zopefoundation/Products.ZSQLMethods/blob/7975c1a3c3d34f8fdc6cd667e08981dc909e3c24/src/Shared/DC/ZRDB/Connection.py#L207 is not Python 2 compatible.

I tried to see if it is covered by tests but https://coveralls.io/github/zopefoundation/Products.ZSQLMethods just hast `src/Products`.

**Comment by dataflake** [comment]
Running `bin/test` manually and increasing verbosity proves that the tests in `src/Shared` are found and executed. There just aren't enough tests. I entered one of the `tox` environments, manually installed `coverage` so I could execute `bin/coverage run bin/test` and then `bin/coverage html`. That specific file, `Connection.py`, has just 49% coverage.

**Comment by dataflake** [comment]
A small fix to the coverage run configuration now includes everything under `src`

**Comment by icemac** [comment]
Thank you for fixing the the coverage issue, it is now clear that the code referenced in the original description is actually untested.
