### ISSUE TITLE
Not working in Zope 4 master branch.

### ISSUE THREAD

**Issue by garrysadd** [zopefoundation/Products.ZSQLMethods#9]
I get this when trying to add a method in ZMI:

Resource not found

Sorry, the requested resource does not exist.
Check the URL and try again.

Resource: manage_manage_addZSQLMethod POST

**Comment by tseaver** [comment]
@garrysadd Can you please post the URL path of the form which triggers this error?

Also, can you post the output of `pip freeze`?

**Comment by garrysadd** [comment]
URL:http://localhost:8080/manage_manage_addZSQLMethod
Pip Freeze:

AccessControl==4.0b4
Acquisition==4.4.4
AuthEncoding==4.0.0
beautifulsoup4==4.6.3
BTrees==4.5.0
Chameleon==3.2
DateTime==4.2
DocumentTemplate==3.0b3
ExtensionClass==4.3.0
five.globalrequest==99.1
five.localsitemanager==3.1
funcsigs==1.0.2
futures==3.2.0
ipaddress==1.0.22
Missing==4.0.1
mock==2.0.0
MultiMapping==4.0
PasteDeploy==1.5.2
pbr==4.0.3
Persistence==3.0b3
persistent==4.2.4.2
Products.BTreeFolder2==4.0.0
Products.PythonScripts==4.1
Products.ZCatalog==4.1
Products.ZCTextIndex==4.0.2
Products.ZSQLMethods==3.0.3
psycopg2==2.7.5
python-gettext==3.0
pytz==2018.4
Record==3.4
RestrictedPython==4.0b4
six==1.11.0
SQLAlchemy==1.2.11
transaction==2.2.1
trollius==2.2
waitress==1.1.0
WebOb==1.8.1
WebTest==2.0.29
WSGIProxy2==0.4.4
z3c.pt==3.1.0
z3c.sqlalchemy==1.4.0
zc.lockfile==1.3.0
ZConfig==3.2.0
zdaemon==4.2.0
ZEO==5.2.0
zExceptions==4.0
ZODB==5.4.0
zodbpickle==1.0.1
-e git+https://github.com/zopefoundation/Zope.git@c9002f06a5a94841d2cbf6b51d366d3b7f633297#egg=Zope
zope.annotation==4.6.0
zope.browser==2.2.0
zope.browsermenu==4.3.0
zope.browserpage==4.2.0
zope.browserresource==4.2.1
zope.cachedescriptors==4.3.1
zope.component==4.4.1
zope.componentvocabulary==2.1.0
zope.configuration==4.1.0
zope.container==4.2.1
zope.contentprovider==4.1.0
zope.contenttype==4.3.0
zope.datetime==4.2.0
zope.deferredimport==4.2.1
zope.deprecation==4.3.0
zope.dottedname==4.2
zope.event==4.3.0
zope.exceptions==4.2.0
zope.filerepresentation==4.2.0
zope.formlib==4.4
zope.globalrequest==1.4
zope.i18n==4.3.1
zope.i18nmessageid==4.1.0
zope.interface==4.5.0
zope.lifecycleevent==4.2.0
zope.location==4.1.0
zope.pagetemplate==4.3.0
zope.processlifetime==2.2.0
zope.proxy==4.3.0
zope.ptresource==4.1.0
zope.publisher==4.3.2
zope.ramcache==2.2.0
zope.schema==4.5.0
zope.security==4.2.2
zope.sendmail==4.1.0
zope.sequencesort==4.0.1
zope.site==4.1.0
zope.size==4.2.0
zope.sqlalchemy==1.0
zope.structuredtext==4.2.0
zope.tal==4.3.1
zope.tales==4.2.0
zope.testbrowser==5.2.4
zope.testing==4.6.2
zope.testrunner==4.8.1
zope.traversing==4.2.0
zope.viewlet==4.1.0
Zope2==4.0b1
ZServer==4.0b1

**Comment by tseaver** [comment]
Is that URL the one in your browser's URL bar before you push the form's button, or after?  I need to know the "before".

**Comment by garrysadd** [comment]
It is the URL of the form submit to add a method during inspecting the source of the form.

**Comment by tseaver** [comment]
I want to know the URL path of the page which contains the form, in order to diagnose how the malformed `action` was generated.

**Comment by garrysadd** [comment]
I'm in the ZMI and clicking add ZSQLmethod from the add select box. The URL from that appears to be manage_addProduct/ZSQLMethods/add
The URL in browser is localhost:8080/manage_main

Am I getting this mixed up?

**Comment by sallner** [comment]
This problem is actually rooted in [Zope-ZMI](https://github.com/zopefoundation/Zope/blob/master/src/zmi/styles/resources/zmi_base.js#L19), so we use the ticket there. The JS does not handle the splitting of actions correctly if the action name occurs more than once in the URL.
